(()=>{
const K='morning-intelligence-report:dbt-checkins:v1';
const F={
Happy:{color:'#e1b75b',soft:'#f7edcf',middle:{Playful:['Aroused','Cheeky'],Content:['Free','Joyful'],Interested:['Curious','Inquisitive'],Proud:['Successful','Confident'],Accepted:['Respected','Valued'],Powerful:['Courageous','Creative'],Peaceful:['Loving','Thankful'],Trusting:['Sensitive','Intimate'],Optimistic:['Hopeful','Inspired']}},
Surprised:{color:'#e29a61',soft:'#f8e3d2',middle:{Startled:['Shocked','Dismayed'],Confused:['Disillusioned','Perplexed'],Amazed:['Astonished','Awe'],Excited:['Eager','Energetic']}},
'Bad / Off':{color:'#8c8993',soft:'#e9e7eb',middle:{Bored:['Indifferent','Apathetic'],Busy:['Pressured','Rushed'],Stressed:['Overwhelmed','Out of control'],Tired:['Sleepy','Unfocused']}},
Fearful:{color:'#9386bd',soft:'#ebe7f5',middle:{Scared:['Helpless','Frightened'],Anxious:['Overwhelmed','Worried'],Insecure:['Inadequate','Inferior'],Weak:['Worthless','Insignificant'],Rejected:['Excluded','Persecuted'],Threatened:['Nervous','Exposed']}},
Angry:{color:'#d97873',soft:'#f5dfdc',middle:{'Let down':['Betrayed','Resentful'],Humiliated:['Disrespected','Ridiculed'],Bitter:['Indignant','Violated'],Mad:['Furious','Jealous'],Aggressive:['Provoked','Hostile'],Frustrated:['Infuriated','Annoyed'],Distant:['Withdrawn','Numb'],Critical:['Skeptical','Dismissive']}},
Disgusted:{color:'#7ea88d',soft:'#e3eee6',middle:{Disapproving:['Judgmental','Embarrassed'],Disappointed:['Appalled','Revolted'],Awful:['Nauseated','Detestable'],Repelled:['Horrified','Hesitant']}},
Sad:{color:'#77a8c5',soft:'#e2edf4',middle:{Hurt:['Disappointed','Embarrassed'],Depressed:['Inferior','Empty'],Guilty:['Remorseful','Ashamed'],Despair:['Grief','Powerless'],Vulnerable:['Victimized','Fragile'],Lonely:['Isolated','Abandoned']}}
};
const S={
'WISE MIND':{module:'Mindfulness',file:'WISE MIND Skill.png',why:'Make room for both emotion and facts before deciding what deserves action.',now:'Name the emotion-mind story. Name the reasonable-mind facts. Then choose a response that respects both.',prompt:'What does emotion mind know that matters? What does reasonable mind know that matters? What answer remains when neither side gets to erase the other?'},
STOP:{module:'Distress Tolerance',file:'STOP Skill.png',why:'Create space between the emotion and the behavior before an impulse chooses for you.',now:'Stop. Take a step back. Observe the urge, facts, and body. Proceed only after you can choose instead of react.',prompt:'What happens if you obey the first urge? What becomes possible if you wait long enough to choose?'},
TIPP:{module:'Distress Tolerance',file:'TIPP Skill.png',why:'Your body is too activated for a thinking skill to get much traction yet.',now:'Choose one safe TIPP component. One body intervention first, then reassess.',prompt:'Which part of TIPP can you do in the next two minutes, and what is your intensity before and after?'},
'RADICAL ACCEPTANCE':{module:'Distress Tolerance',file:'Radical Acceptance Skill.png',why:'The pain is real, but fighting an unchangeable reality is adding suffering.',now:'State the reality without should, fair, or why. Separate what cannot change from what you can still choose.',prompt:'What exact fact are you refusing to let be true? What changes if you simply acknowledge it?'},
'OPPOSITE ACTION':{module:'Emotion Regulation',file:'Opposite Action Skill.png',why:'The emotion is generating an action urge that may strengthen the state you want to move through.',now:'Name the urge. Identify its behavioral opposite. Do the opposite enough to collect new information.',prompt:'What is the emotion telling you to do? If that urge is ineffective, what is its behavioral opposite?'},
'PROBLEM SOLVING':{module:'Emotion Regulation',file:'Problem Solving Skill.png',why:'There is a real, changeable problem here. A concrete next step may help more than more analysis.',now:'Describe the problem, define the goal, brainstorm options, and choose the smallest useful action.',prompt:'What part is actually solvable today? What outcome would count as progress rather than perfection?'},
'DEAR MAN':{module:'Interpersonal Effectiveness',file:'DEAR MAN Skill.png',why:'The main task is communicating an objective clearly: asking, saying no, setting a limit, or requesting change.',now:'Write the D, E, and A in one sentence each before the conversation. Decide what reinforcement matters.',prompt:'What exactly are you asking for? Can you describe the facts without building the prosecution case first?'},
FAST:{module:'Interpersonal Effectiveness',file:'FAST Skill.png',why:'The relationship matters, but not at the cost of abandoning your values or self-respect.',now:'Identify the value you will not violate. Remove unnecessary apology, exaggeration, and self-erasure.',prompt:'If you walked away still respecting yourself, what would you have said, not said, or refused to pretend?'}
};
const COMING={Mindfulness:['WHAT Skills','HOW Skills'],'Distress Tolerance':['Self-Soothe','IMPROVE'],'Emotion Regulation':['Check the Facts','ABC PLEASE','Cope Ahead'],'Interpersonal Effectiveness':['GIVE']};
const MAP={impulse:'STOP',body:'TIPP',facts:'WISE MIND',urge:'OPPOSITE ACTION',change:'PROBLEM SOLVING',accept:'RADICAL ACCEPTANCE',ask:'DEAR MAN',respect:'FAST'};
const st={family:null,middle:null,outer:new Set(),decision:null,body:new Set(),skill:null,cal:new Date(new Date().getFullYear(),new Date().getMonth(),1)};
const $=q=>document.querySelector(q),$$=q=>[...document.querySelectorAll(q)];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const asset=f=>'assets/images/'+encodeURIComponent(f);
const entries=()=>{try{let x=JSON.parse(localStorage.getItem(K)||'[]');return Array.isArray(x)?x:[]}catch{return[]}};
const saveEntries=x=>localStorage.setItem(K,JSON.stringify(x));
const localISO=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function dateHead(){let n=new Date(),h=n.getHours();$('#feelings-greeting').textContent=h<12?'Good morning, Parker.':h<17?'Good afternoon, Parker.':'Good evening, Parker.';$('#feelings-date').textContent=n.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});}
function tabs(){$$('.dbt-tab').forEach(b=>b.onclick=()=>{let t=b.dataset.tab;$$('.dbt-tab').forEach(x=>{let on=x===b;x.classList.toggle('is-active',on);x.setAttribute('aria-selected',on)});$$('.dbt-view').forEach(v=>{let on=v.dataset.view===t;v.hidden=!on;v.classList.toggle('is-active',on)});if(t==='calendar')calendar();if(t==='journal')journal();if(t==='skills')library()})}
function progress(n){$$('.progress-step').forEach(x=>{let v=+x.dataset.progress;x.classList.toggle('is-active',v===n);x.classList.toggle('is-complete',v<n)})}
function familyButtons(){let names=Object.keys(F);$('#family-buttons').innerHTML=names.map((n,i)=>{let a=i*360/names.length;return `<button class="family-wheel-button" type="button" style="--angle:${a}deg;--reverse-angle:${-a}deg" data-family="${esc(n)}">${esc(n)}</button>`}).join('');$$('[data-family]').forEach(b=>b.onclick=()=>chooseFamily(b.dataset.family))}
const chip=(txt,color)=>`<span class="path-chip" style="--path-color:${color}">${esc(txt)}</span>`;
function chooseFamily(n){st.family=n;st.middle=null;st.outer.clear();st.decision=null;st.skill=null;$$('.family-wheel-button').forEach(b=>b.classList.toggle('is-selected',b.dataset.family===n));$('#wheel-center-label').innerHTML=`${esc(n)}<br><small>go outward</small>`;let d=F[n];$('#middle-heading').textContent=`What kind of ${n.toLowerCase()}?`;$('#selection-path-middle').innerHTML=chip(n,d.color);$('#middle-options').innerHTML=Object.keys(d.middle).map(m=>`<button class="middle-option" style="--option-color:${d.color}" data-middle="${esc(m)}">${esc(m)}</button>`).join('');$$('[data-middle]').forEach(b=>b.onclick=()=>chooseMiddle(b.dataset.middle));$('#middle-step').hidden=false;$('#outer-step').hidden=true;$('#context-step').hidden=true;$('#skill-result').hidden=true;progress(2);$('#middle-step').scrollIntoView({behavior:'smooth',block:'start'})}
function chooseMiddle(n){st.middle=n;st.outer.clear();let d=F[st.family];$$('[data-middle]').forEach(b=>b.classList.toggle('is-selected',b.dataset.middle===n));$('#selection-path-outer').innerHTML=chip(st.family,d.color)+chip(n,d.color);$('#outer-heading').textContent=`Inside ${n.toLowerCase()}, what fits?`;$('#outer-options').innerHTML=d.middle[n].map(o=>`<button class="outer-option" style="--option-color:${d.color}" data-outer="${esc(o)}">${esc(o)}</button>`).join('');$$('[data-outer]').forEach(b=>b.onclick=()=>toggleOuter(b));$('#continue-to-context').disabled=true;$('#outer-step').hidden=false;$('#context-step').hidden=true;$('#skill-result').hidden=true;progress(3);$('#outer-step').scrollIntoView({behavior:'smooth',block:'start'})}
function toggleOuter(b){let n=b.dataset.outer;st.outer.has(n)?st.outer.delete(n):st.outer.add(n);b.classList.toggle('is-selected',st.outer.has(n));$('#continue-to-context').disabled=!st.outer.size}
function openContext(){if(!st.outer.size)return;let d=F[st.family],words=[...st.outer];$('#chosen-feelings-summary').style.setProperty('--family-color',d.color);$('#chosen-feelings-summary').style.setProperty('--family-soft',d.soft);$('#chosen-feelings-summary').innerHTML=`<strong>${esc(words.join(' + '))}</strong><br><span>${esc(st.family)} → ${esc(st.middle)}</span>`;$('#context-step').hidden=false;progress(4);$('#context-step').scrollIntoView({behavior:'smooth',block:'start'})}
function context(){$('#continue-to-context').onclick=openContext;$('#intensity').oninput=e=>$('#intensity-output').textContent=`${e.target.value} / 10`;$$('#decision-options button').forEach(b=>b.onclick=()=>{st.decision=b.dataset.decision;$$('#decision-options button').forEach(x=>x.classList.toggle('is-selected',x===b));$('#recommend-skill').disabled=false});$$('#body-context-options button').forEach(b=>b.onclick=()=>{let v=b.dataset.body;st.body.has(v)?st.body.delete(v):st.body.add(v);b.classList.toggle('is-selected',st.body.has(v))});$('#recommend-skill').onclick=recommend}
function recommend(){let intensity=+$('#intensity').value,name=MAP[st.decision];if(intensity>=9&&!['ask','respect'].includes(st.decision))name='TIPP';st.skill=name;let s=S[name];$('#recommended-skill-name').textContent=name;$('#recommended-skill-why').textContent=s.why;$('#recommended-skill-now').textContent=s.now;$('#recommended-skill-image').src=asset(s.file);$('#recommended-skill-image').alt=`${name} DBT skill reminder`;$('#skill-result').hidden=false;$('#skill-result').scrollIntoView({behavior:'smooth',block:'start'})}
function skillActions(){$('#open-recommended-card').onclick=()=>modal(st.skill);$('#recommended-image-button').onclick=()=>modal(st.skill);$('#save-checkin').onclick=saveCheckin}
function saveCheckin(){if(!st.skill||!st.outer.size)return;let now=new Date(),list=entries();list.push({id:crypto.randomUUID?.()||String(Date.now()),timestamp:now.toISOString(),date:localISO(now),family:st.family,middle:st.middle,outer:[...st.outer],intensity:+$('#intensity').value,decision:st.decision,skill:st.skill,bodyContext:[...st.body],note:$('#checkin-note').value.trim()});saveEntries(list);$('#save-status').textContent='Saved. Your calendar and journal are updated.';calendar();journal()}
function reset(){st.family=st.middle=st.decision=st.skill=null;st.outer.clear();st.body.clear();$$('.family-wheel-button,.middle-option,.outer-option,#decision-options button,#body-context-options button').forEach(b=>b.classList.remove('is-selected'));$('#wheel-center-label').innerHTML='How are you<br>feeling?';['middle-step','outer-step','context-step','skill-result'].forEach(id=>$('#'+id).hidden=true);$('#continue-to-context').disabled=true;$('#recommend-skill').disabled=true;$('#intensity').value=5;$('#intensity-output').textContent='5 / 10';$('#checkin-note').value='';$('#save-status').textContent='';progress(1);$('#family-step').scrollIntoView({behavior:'smooth'})}
const pretty=v=>({period:'period','hormonal-shift':'possible hormonal shift',sleep:'poor sleep',pain:'pain / discomfort','hot-flash':'hot flash / night sweats',overstimulated:'overstimulated',unsure:'not sure'}[v]||v);
function calendar(){let grid=$('#mood-calendar-grid');if(!grid)return;let list=entries(),c=st.cal,y=c.getFullYear(),m=c.getMonth(),first=new Date(y,m,1),start=new Date(y,m,1-first.getDay()),by={};list.forEach(e=>(by[e.date]??=[]).push(e));$('#calendar-month-label').textContent=first.toLocaleDateString(undefined,{month:'long',year:'numeric'});let today=localISO(new Date()),cells=[];for(let i=0;i<42;i++){let d=new Date(start);d.setDate(start.getDate()+i);let iso=localISO(d),es=by[iso]||[],fd=es.length?F[es.at(-1).family]:null,dots=es.slice(-5).map(e=>`<i style="--dot:${F[e.family]?.color||'#8c8993'}"></i>`).join('');cells.push(`<button class="mood-day ${d.getMonth()!==m?'is-outside':''} ${iso===today?'is-today':''} ${es.length?'has-entry':''}" data-date="${iso}" style="--day-color-soft:${fd?.soft||'#fff'}"><span class="mood-day-number">${d.getDate()}</span><span class="mood-day-dots">${dots}</span></button>`)}grid.innerHTML=cells.join('');grid.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>dayDetail(b.dataset.date));let prefix=`${y}-${String(m+1).padStart(2,'0')}`,me=list.filter(e=>e.date.startsWith(prefix)),days=new Set(me.map(e=>e.date)).size,counts={};me.forEach(e=>counts[e.family]=(counts[e.family]||0)+1);let common=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0]?.[0];$('#calendar-stats').innerHTML=`<div class="calendar-stat"><strong>${days}</strong><span>check-in days</span></div><div class="calendar-stat"><strong>${me.length}</strong><span>check-ins</span></div>${common?`<div class="calendar-stat"><strong>${esc(common)}</strong><span>most logged</span></div>`:''}`}
function dayDetail(date){let es=entries().filter(e=>e.date===date).sort((a,b)=>a.timestamp.localeCompare(b.timestamp)),box=$('#calendar-day-detail'),label=new Date(date+'T12:00').toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});box.innerHTML=`<h3 class="day-detail-heading">${esc(label)}</h3>`+(es.length?es.map(e=>`<article class="day-entry"><div class="day-entry-top"><div><div class="day-entry-feelings" style="color:${F[e.family]?.color||'#273044'}">${esc(e.outer.join(' + '))}</div><div class="day-entry-meta">${esc(e.family)} → ${esc(e.middle)} · intensity ${e.intensity}/10</div></div><div class="day-entry-meta">${new Date(e.timestamp).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</div></div><div class="day-entry-meta">Skill: ${esc(e.skill)}${e.bodyContext?.length?' · Context: '+e.bodyContext.map(pretty).join(', '):''}</div>${e.note?`<p class="day-entry-note">${esc(e.note)}</p>`:''}</article>`).join(''):'<p class="empty-state">No feelings check-in saved for this day.</p>')}
function journal(){let sel=$('#journal-filter'),list=$('#journal-list');if(sel.options.length===1){Object.keys(F).forEach(x=>sel.add(new Option(x,x)));sel.onchange=journal}let es=entries().filter(e=>sel.value==='all'||e.family===sel.value).sort((a,b)=>b.timestamp.localeCompare(a.timestamp));list.innerHTML=es.length?es.map(e=>{let d=new Date(e.timestamp);return `<article class="journal-entry" style="--entry-color:${F[e.family]?.color||'#8c8993'}"><div class="journal-color"></div><div><div class="journal-entry-header"><div><h3>${esc(e.outer.join(' + '))}</h3><div class="journal-meta">${esc(e.family)} → ${esc(e.middle)} · intensity ${e.intensity}/10</div></div><time>${d.toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}<br>${d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</time></div>${e.note?`<p>${esc(e.note)}</p>`:'<p class="journal-meta">No note saved for this check-in.</p>'}<span class="journal-skill">DBT: ${esc(e.skill)}</span></div></article>`}).join(''):'<div class="checkin-card"><p class="empty-state">No saved check-ins in this view yet. Your first one will land here.</p></div>'}
function library(){let ids={Mindfulness:'#skills-mindfulness','Distress Tolerance':'#skills-distress','Emotion Regulation':'#skills-emotion','Interpersonal Effectiveness':'#skills-interpersonal'};Object.entries(ids).forEach(([mod,id])=>{let h=$(id),ready=Object.entries(S).filter(([,s])=>s.module===mod);h.innerHTML=ready.map(([n,s])=>`<button class="skill-card" data-skill="${esc(n)}"><img src="${asset(s.file)}" alt="${esc(n)} DBT infographic" loading="lazy"><span class="skill-card-footer"><strong>${esc(n)}</strong><span>${esc(mod)}</span></span></button>`).join('')+(COMING[mod]||[]).map(n=>`<div class="skill-card is-coming"><strong>${esc(n)}</strong><span>Infographic coming next</span></div>`).join('');h.querySelectorAll('[data-skill]').forEach(b=>b.onclick=()=>modal(b.dataset.skill))})}
function modal(n){let s=S[n];if(!s)return;$('#skill-modal-module').textContent=`DBT • ${s.module}`;$('#skill-modal-title').textContent=n;$('#skill-modal-image').src=asset(s.file);$('#skill-modal-image').alt=`${n} DBT skill reminder`;$('#skill-modal-prompt').textContent=s.prompt;$('#skill-modal').hidden=false;document.body.classList.add('modal-open');$('#skill-modal-close').focus()}
function closeModal(){$('#skill-modal').hidden=true;document.body.classList.remove('modal-open')}
function init(){dateHead();tabs();familyButtons();context();skillActions();$('#reset-checkin').onclick=reset;$('#calendar-prev').onclick=()=>{st.cal=new Date(st.cal.getFullYear(),st.cal.getMonth()-1,1);calendar()};$('#calendar-next').onclick=()=>{st.cal=new Date(st.cal.getFullYear(),st.cal.getMonth()+1,1);calendar()};$('#skill-modal-close').onclick=closeModal;$('#skill-modal-backdrop').onclick=closeModal;document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#skill-modal').hidden)closeModal()});calendar();journal();library()}
document.addEventListener('DOMContentLoaded',init);
})();
